name: Release
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  bump:
    uses: lisandra-dev/reusable-workflows/.github/workflows/bump.yaml@main
    with:
      PLUGIN_NAME: copy-reading-in-markdown
      STYLE: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}