name: Release
"on":
  workflow_dispatch:
  push:
    tags:
      - "*"
permissions:
  contents: write
jobs:
  publish:
    uses: lisandra-dev/reusable-workflows/.github/workflows/obsidian-plugin-publish.yaml@main
    with:
        PLUGIN_NAME: "copy-reading-in-markdown"
        STYLE: true
    secrets: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}