name: Release obsidian plugin
"on":
  workflow_dispatch:
  push:
    tags:
      - "*"
permissions:
  contents: write
jobs:
  release:
    if: (github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && inputs.bump == false)
    uses: lisandra-dev/reusable-workflows/.github/workflows/obsidian-plugin-release.yaml@main
    with:
        PLUGIN_NAME: "copy-reading-in-markdown"
        STYLE: true
    secrets: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  bump-version:
    if: ${{ github.event.inputs.bump == true }}
    uses: lisandra-dev/reusable-workflows/.github/workflows/obsidian-plugin-bump-version.yaml@main
    with:
        PLUGIN_NAME: "copy-reading-in-markdown"
        STYLE: true
    secrets: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
  
